services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - data:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
volumes:
  data:
    external: false
