services:
  couchdb:
    image: couchdb
    restart: always
    ports:
      - '5984:5984'
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
      - COUCHDB_QUERY_SERVER_JAVASCRIPT="./bin/couchjs ./share/server/main.js -S 3355443000"
    volumes:
      - data:/opt/couchdb/data
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
volumes:
  cache:
    external: false
  data:
    external: false
